name: Feature request
description: Request a new feature (Provide link/api documents of the requested feature.)
labels: [feature request]
body:
  - type: markdown
    attributes:
      value: |
        We can only implement features/engines that their API Server is available and has documents for them.
        We do not implement unreleased features.
        Use Discord for questions: https://discord.gg/7jgfP6j4Tc
  - type: dropdown
    id: part
    attributes:
      label: Which part is the feature request for?
      options:
        - YouTube
        - Spotify
        - SoundCloud
        - Deezer
        - Other
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Feature
      description: A clear and concise description of what the problem is, or what feature you want to be implemented.
      placeholder: I'm always frustrated when..., YouTube has recently released..., A good addition would be...
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Ideal solution or implementation
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternative solutions or implementations
      description: A clear and concise description of any alternative solutions or features you have considered.
  - type: textarea
    id: additional-context
    attributes:
      label: Other context
      description: Any other context, screenshots, or file uploads that help us understand your feature request.